### ISSUE TITLE
Does not run as a console app on Mac

### ISSUE THREAD

**Issue by justinjstark** [justinjstark/SmtpRouter#1]
➜  src git:(master) dotnet run --project SmtpRouter/SmtpRouter.csproj
Configuration Result:
[Success] Name SMTP Router
[Success] Description An SMTP server which reroutes emails for a test environment
[Success] ServiceName SMTP Router
Topshelf v4.1.0.172, .NET Framework v4.0.30319.42000
Topshelf.Runtime.Windows.WindowsHostEnvironment Error: 0 : Unable to get parent process (ignored), System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libkernel32.dll, 1): image not found
   at Topshelf.Runtime.Windows.Kernel32.CreateToolhelp32Snapshot(UInt32 dwFlags, UInt32 th32ProcessID)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.GetParent(Process child)
Topshelf.HostFactory Error: 0 : The service terminated abnormally, System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.
   at System.ServiceProcess.ServiceController.GetServices()
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.IsServiceListed(String serviceName)
   at Topshelf.Hosts.ConsoleRunHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by justinjstark** [comment]
Now uses Service Worker
